#!/usr/bin/env python3
import os
import subprocess
import sys


def main():
    if len(sys.argv) < 3:
        print("Uso: script.py [-i imagen | -v video] ruta")
        sys.exit(1)

    modo = sys.argv[1]
    ruta_wallpaper = sys.argv[2]
    ruta_frame = os.path.expanduser("~/.cache/wal/animated/frame.png")
    os.makedirs(os.path.dirname(ruta_frame), exist_ok=True)

    if modo == "-i":
        subprocess.run(["wal", "-i", ruta_wallpaper])

    elif modo == "-v":
        subprocess.run(
            [
                "ffmpeg",
                "-i",
                ruta_wallpaper,
                "-vf",
                "select=eq(n\\,100)",
                "-vframes",
                "1",
                ruta_frame,
            ],
            check=True,
        )

        subprocess.run(["wal", "-i", ruta_frame])

        subprocess.run(
            ["pkill", "mpvpaper"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
        )

        subprocess.Popen(
            ["mpvpaper", "-o", "loop", "no-audio", "--hwdec=auto", "*", ruta_wallpaper],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )

    else:
        print("Error: argumento inválido [-i imagen | -v video]")
        sys.exit(1)


if __name__ == "__main__":
    main()
